version: '3.3'

services:
  tests:
    build: .
    container_name: shopping_tests_container
    command: >
        sh -c "flask db upgrade && pytest tests/"
    volumes:
      - .:/shopping
      - ./instance:/shopping/instance
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: nouchka/sqlite3
    container_name: shopping_db_container_test
    volumes:
      - ./instance:/shopping/instance
    env_file:
      - .env
