"""Created Tables

Revision ID: 75c8daf197b6
Revises: 
Create Date: 2024-05-21 20:00:37.956138

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
from flask import current_app

from simple_flask import db
from simple_flask.core.db_conf import parse_sql_script
from simple_flask.core.utils import init_products, drop_all_tables_sqlite

revision = '75c8daf197b6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    if not current_app.config['USE_RAW_QUERY_DB_INIT']:
        op.create_table('product',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=20), nullable=False),
        sa.Column('cost', sa.Numeric(precision=10, scale=2), nullable=False),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_table('orders',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('quantity', sa.Integer(), nullable=False),
        sa.Column('buyer', sa.String(length=100), nullable=False),
        sa.Column('cost', sa.Integer(), nullable=False),
        sa.Column('product_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        init_products()
    else:
        parse_sql_script()
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    if not current_app.config['USE_RAW_QUERY_DB_INIT']:
        op.drop_table('orders')
        op.drop_table('product')
    else:
        with db.engine.connect() as connection:
            drop_all_tables_sqlite(connection)
    # ### end Alembic commands ###
